version: '3.8'
services:

  frontend:
    image: my-new-frontend:2
    environment:
      - REACT_APP_BACKEND_URL=backend:8080

  backend:
    image: my-new-backend:2
    environment:
      - REDIS_HOST=my-redis
      - POSTGRES_HOST=postgres_test
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=nice
      - POSTGRES_DB=postgres

  postgres_test:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=nice
    restart: unless-stopped
    volumes: 
      - ./database:/var/lib/postgresql/data

  nginx:
    image: nginx
    ports:
      - 80:80
    volumes:
      - type: bind
        source: ./nginx.conf
        target: /etc/nginx/nginx.conf
    depends_on:
      - frontend
      - backend
      
  my-redis:
    image: redis
    